### PR TITLE
Reposition the logo within a non-negative frame

### PR DESCRIPTION
**Pull request by lukecarbis**
Some SVG viewers, including Mac OS X and Affinity Designer, don't
properly handle frames with negative top and left points.

This commit recreates the frame with a 0 0 top left, and centers
the logo both vertically and horizontally within it.

### CODE REVIEW

**Comment by lukecarbis** [comment]
@westonruter Does this resolve #3? If not, what else needs to happen?

**Comment by westonruter** [comment]
@lukecarbis wow, how did you do this?

**Comment by westonruter** [comment]
@lukecarbis this point here: 

>  Draw each letter relative to 0,0 on coordinate system, then translate into place.

Is about basically having each letter in a separate `g` with a 0,0 coordinate system and then translate it into position. This is not really necessary though.

But the only thing I think that should be changed is the left edge of the X should be flush with the viewport left edge. In other words, there should be no margins at all between the viewport and the letters. Any margins should be added in the context of wherever the logo is embedded. Is this something you can do?

**Comment by lukecarbis** [comment]
@westonruter with Affinity Designer and some math.

I can make the margin change. Does it also go for the top and bottom edge as well? Or should there be some bottom margin in order to vertically centre the logo?

**Comment by westonruter** [comment]
I think the view port should exactly correspond to the top, right, bottom,
left edges of the logo. Any additional margin can be added by whatever is
embedding the logo.

**Comment by lukecarbis** [comment]
@westonruter How's that?

**Comment by westonruter** [comment]
:heart: :heart: :heart:

**Pull request merged**
